# Generated by Django 2.1.7 on 2019-10-21 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('language', models.CharField(blank=True, choices=[('English', 'English'), ('Sesotho', 'Sesotho'), ('IsiXhosa', 'IsiXhosa')], max_length=15, null=True)),
                ('pronounciation_is_easy_num_votes', models.IntegerField(default=0)),
                ('pronounciation_is_average_num_votes', models.IntegerField(default=0)),
                ('pronounciation_is_difficult_num_votes', models.IntegerField(default=0)),
                ('pronounciation_not_sure_num_votes', models.IntegerField(default=0)),
                ('is_heteronym_num_votes', models.IntegerField(default=0)),
                ('is_not_heteronym_num_votes', models.IntegerField(default=0)),
                ('heteronym_not_sure_num_votes', models.IntegerField(default=0)),
                ('sign_is_easy_num_votes', models.IntegerField(default=0)),
                ('sign_is_average_num_votes', models.IntegerField(default=0)),
                ('sign_is_difficult_num_votes', models.IntegerField(default=0)),
                ('sign_not_sure_num_votes', models.IntegerField(default=0)),
                ('is_heteronym_sign_num_votes', models.IntegerField(default=0)),
                ('is_not_heteronym_sign_num_votes', models.IntegerField(default=0)),
                ('heteronym_sign_not_sure_num_votes', models.IntegerField(default=0)),
                ('antonyms', models.ManyToManyField(blank=True, related_name='_language_antonyms_+', to='corpus.Language')),
                ('synonyms', models.ManyToManyField(blank=True, related_name='_language_synonyms_+', to='corpus.Language')),
                ('translations', models.ManyToManyField(blank=True, related_name='_language_translations_+', to='corpus.Language')),
            ],
            options={
                'verbose_name': 'All',
                'verbose_name_plural': 'All',
            },
        ),
        migrations.CreateModel(
            name='LanguageMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField(blank=True, null=True)),
                ('usage', models.TextField(blank=True, null=True)),
                ('part_of_speech', models.CharField(blank=True, choices=[('verb', 'verb'), ('noun', 'noun'), ('adjective', 'adjective'), ('adverb', 'adverb'), ('pronoun', 'pronoun'), ('preposition', 'preposition'), ('conjunction', 'conjunction'), ('particle', 'particle'), ('article', 'article'), ('interjection', 'interjection'), ('exclamation', 'exclamation'), ('possessive determiner', 'possessive determiner')], max_length=50, null=True)),
                ('tense', models.CharField(blank=True, choices=[('n/a', 'n/a'), ('past', 'past'), ('present', 'present'), ('future', 'future')], max_length=50, null=True)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.Language')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Text Metadata',
                'verbose_name_plural': 'Text Metadata',
            },
        ),
        migrations.CreateModel(
            name='SignMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('sign_is_accurate_num_votes', models.IntegerField(default=0)),
                ('sign_is_not_accurate_num_votes', models.IntegerField(default=0)),
                ('sign_accuracy_not_sure_num_votes', models.IntegerField(default=0)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.Language')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sign_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sign Metadata',
                'verbose_name_plural': 'Sign Metadata',
            },
        ),
        migrations.CreateModel(
            name='SpeechMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='')),
                ('pronounciation_is_accurate_num_votes', models.IntegerField(default=0)),
                ('pronounciation_is_not_accurate_num_votes', models.IntegerField(default=0)),
                ('pronounciation_accuracy_not_sure_num_votes', models.IntegerField(default=0)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.Language')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speech_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Speech Metadata',
                'verbose_name_plural': 'Speech Metadata',
            },
        ),
    ]
