# Generated by Django 2.1.7 on 2019-10-24 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conjugation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='word_base_form', to='corpus.Language')),
                ('past_simple', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='corpus.Language')),
            ],
        ),
    ]
