# Generated by Django 2.1.7 on 2019-10-24 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_conjugation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conjugation',
            name='base_form',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='past_simple',
        ),
        migrations.AddField(
            model_name='language',
            name='base_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base', to='corpus.Language'),
        ),
        migrations.AddField(
            model_name='language',
            name='past_simple',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='past', to='corpus.Language'),
        ),
        migrations.DeleteModel(
            name='Conjugation',
        ),
    ]
