# Generated by Django 2.1.7 on 2019-10-24 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_auto_20191024_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conjugation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='language',
            name='base_form',
        ),
        migrations.RemoveField(
            model_name='language',
            name='past_simple',
        ),
        migrations.AddField(
            model_name='conjugation',
            name='base_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base', to='corpus.Language'),
        ),
        migrations.AddField(
            model_name='conjugation',
            name='past_participle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='past_singular_form', to='corpus.Language'),
        ),
        migrations.AddField(
            model_name='conjugation',
            name='past_simple',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='past_simple_form', to='corpus.Language'),
        ),
        migrations.AddField(
            model_name='conjugation',
            name='present_participle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gerund', to='corpus.Language'),
        ),
        migrations.AddField(
            model_name='conjugation',
            name='third_person_singular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_person_singular_form', to='corpus.Language'),
        ),
    ]
