# Generated by Django 2.1.7 on 2019-10-30 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_auto_20191024_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagemetadata',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='corpus.Language'),
        ),
    ]
