# Generated by Django 2.1.7 on 2019-10-30 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0005_auto_20191030_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagemetadata',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_metadata', to='corpus.Language'),
        ),
    ]
