# Generated by Django 2.1.7 on 2019-11-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0006_auto_20191030_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='num_searches',
            field=models.IntegerField(default=0),
        ),
    ]
