# Generated by Django 2.1.7 on 2019-11-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0007_language_num_searches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='heteronym_not_sure_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='language',
            name='heteronym_sign_not_sure_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='language',
            name='is_heteronym_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='language',
            name='is_heteronym_sign_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='language',
            name='is_not_heteronym_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='language',
            name='is_not_heteronym_sign_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Sesotho', 'Sesotho'), ('IsiXhosa', 'IsiXhosa')], default='Unlabeled', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='num_searches',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='language',
            name='pronounciation_is_average_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='language',
            name='pronounciation_is_difficult_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='language',
            name='pronounciation_is_easy_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='language',
            name='pronounciation_not_sure_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='language',
            name='sign_is_average_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='language',
            name='sign_is_difficult_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='language',
            name='sign_is_easy_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='language',
            name='sign_not_sure_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='signmetadata',
            name='sign_accuracy_not_sure_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='signmetadata',
            name='sign_is_accurate_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='signmetadata',
            name='sign_is_not_accurate_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='signmetadata',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='speechmetadata',
            name='audio',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='speechmetadata',
            name='pronounciation_accuracy_not_sure_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='speechmetadata',
            name='pronounciation_is_accurate_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='speechmetadata',
            name='pronounciation_is_not_accurate_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
