# Generated by Django 2.1.7 on 2019-11-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0008_auto_20191107_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Sesotho', 'Sesotho'), ('IsiXhosa', 'IsiXhosa')], default='Unlabeled', max_length=15),
        ),
    ]
