# Generated by Django 2.1.7 on 2019-11-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0012_auto_20191107_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Sesotho', 'Sesotho'), ('IsiXhosa', 'IsiXhosa')], default='', max_length=15, null=True),
        ),
    ]
