# Generated by Django 2.1.7 on 2019-12-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0013_auto_20191108_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='text',
            field=models.TextField(),
        ),
    ]
