# Generated by Django 3.1.6 on 2021-02-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0014_auto_20191211_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='single_word',
            field=models.BooleanField(default=False),
        ),
    ]
