# Generated by Django 3.1.6 on 2021-02-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0015_language_single_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(blank=True, choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), ('e', 'e'), ('f', 'f'), ('g', 'g'), ('h', 'h'), ('i', 'i'), ('j', 'j'), ('k', 'k'), ('l', 'l'), ('m', 'm'), ('n', 'n'), ('o', 'o'), ('p', 'p'), ('q', 'q'), ('r', 'r'), ('s', 's'), ('t', 't'), ('u', 'u'), ('v', 'v'), ('w', 'w'), ('x', 'x'), ('y', 'y'), ('z', 'z')], default='', max_length=2, null=True)),
                ('start', models.IntegerField(blank=True, default=0)),
                ('end', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
