# Generated by Django 3.1.6 on 2021-03-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0016_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Sesotho', 'Sesotho'), ('IsiXhosa', 'IsiXhosa')], default='', max_length=15, null=True),
        ),
    ]
