# Generated by Django 3.1.6 on 2021-03-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0017_index_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'Index', 'verbose_name_plural': 'Indices'},
        ),
        migrations.AddField(
            model_name='speechmetadata',
            name='the_audio_does_not_match_the_text_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='speechmetadata',
            name='the_audio_does_not_play_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='speechmetadata',
            name='the_audio_is_aligned_with_the_text_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='speechmetadata',
            name='the_audio_is_offensive_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='speechmetadata',
            name='the_audio_is_too_fast_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='speechmetadata',
            name='the_audio_is_too_slow_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='speechmetadata',
            name='the_audio_speed_is_okay_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='speechmetadata',
            name='the_audio_volume_is_too_high_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='speechmetadata',
            name='the_audio_volume_is_too_low_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='speechmetadata',
            name='the_text_contains_spelling_errors_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='speechmetadata',
            name='the_text_is_offensive_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='speechmetadata',
            name='translations',
            field=models.ManyToManyField(blank=True, related_name='_speechmetadata_translations_+', to='corpus.SpeechMetadata'),
        ),
    ]
