# Generated by Django 3.1.6 on 2021-03-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0018_auto_20210317_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='signmetadata',
            name='the_text_contains_spelling_errors_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='signmetadata',
            name='the_text_is_offensive_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='signmetadata',
            name='the_video_does_not_match_the_text_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='signmetadata',
            name='the_video_does_not_play_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='signmetadata',
            name='the_video_is_aligned_with_the_text_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='signmetadata',
            name='the_video_is_not_visible_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='signmetadata',
            name='the_video_is_offensive_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='signmetadata',
            name='the_video_is_too_fast_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='signmetadata',
            name='the_video_is_too_slow_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='signmetadata',
            name='the_video_is_visible_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='signmetadata',
            name='the_video_speed_is_okay_num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
