# Generated by Django 3.1.6 on 2021-03-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0019_auto_20210317_0617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signmetadata',
            old_name='the_text_contains_spelling_errors_num_votes',
            new_name='text_offensive_num_votes',
        ),
        migrations.RenameField(
            model_name='signmetadata',
            old_name='the_text_is_offensive_num_votes',
            new_name='text_spelling_errors_num_votes',
        ),
        migrations.RenameField(
            model_name='signmetadata',
            old_name='the_video_does_not_match_the_text_num_votes',
            new_name='video_clipped_num_votes',
        ),
        migrations.RenameField(
            model_name='signmetadata',
            old_name='the_video_does_not_play_num_votes',
            new_name='video_offensive_num_votes',
        ),
        migrations.RenameField(
            model_name='signmetadata',
            old_name='the_video_is_aligned_with_the_text_num_votes',
            new_name='video_plays_num_votes',
        ),
        migrations.RenameField(
            model_name='signmetadata',
            old_name='the_video_is_not_visible_num_votes',
            new_name='video_represents_text_num_votes',
        ),
        migrations.RenameField(
            model_name='speechmetadata',
            old_name='the_audio_does_not_match_the_text_num_votes',
            new_name='audio_clipped_num_votes',
        ),
        migrations.RenameField(
            model_name='speechmetadata',
            old_name='the_audio_does_not_play_num_votes',
            new_name='audio_offensive_num_votes',
        ),
        migrations.RenameField(
            model_name='speechmetadata',
            old_name='the_audio_is_aligned_with_the_text_num_votes',
            new_name='audio_plays_num_votes',
        ),
        migrations.RenameField(
            model_name='speechmetadata',
            old_name='the_audio_is_offensive_num_votes',
            new_name='audio_represents_text_num_votes',
        ),
        migrations.RenameField(
            model_name='speechmetadata',
            old_name='the_audio_is_too_fast_num_votes',
            new_name='text_offensive_num_votes',
        ),
        migrations.RenameField(
            model_name='speechmetadata',
            old_name='the_audio_is_too_slow_num_votes',
            new_name='text_spelling_errors_num_votes',
        ),
        migrations.RemoveField(
            model_name='signmetadata',
            name='the_video_is_offensive_num_votes',
        ),
        migrations.RemoveField(
            model_name='signmetadata',
            name='the_video_is_too_fast_num_votes',
        ),
        migrations.RemoveField(
            model_name='signmetadata',
            name='the_video_is_too_slow_num_votes',
        ),
        migrations.RemoveField(
            model_name='signmetadata',
            name='the_video_is_visible_num_votes',
        ),
        migrations.RemoveField(
            model_name='signmetadata',
            name='the_video_speed_is_okay_num_votes',
        ),
        migrations.RemoveField(
            model_name='speechmetadata',
            name='the_audio_speed_is_okay_num_votes',
        ),
        migrations.RemoveField(
            model_name='speechmetadata',
            name='the_audio_volume_is_too_high_num_votes',
        ),
        migrations.RemoveField(
            model_name='speechmetadata',
            name='the_audio_volume_is_too_low_num_votes',
        ),
        migrations.RemoveField(
            model_name='speechmetadata',
            name='the_text_contains_spelling_errors_num_votes',
        ),
        migrations.RemoveField(
            model_name='speechmetadata',
            name='the_text_is_offensive_num_votes',
        ),
    ]
